// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct PlayerProfileFlat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PlayerProfileFlat GetRootAsPlayerProfileFlat(ByteBuffer _bb) { return GetRootAsPlayerProfileFlat(_bb, new PlayerProfileFlat()); }
  public static PlayerProfileFlat GetRootAsPlayerProfileFlat(ByteBuffer _bb, PlayerProfileFlat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool PlayerProfileFlatBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "FPCS"); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PlayerProfileFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Gold { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Items { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetItemsBytes() { return __p.__vector_as_arraysegment(6); }
  public CharacterModelFlat? Characters(int j) { int o = __p.__offset(8); return o != 0 ? (CharacterModelFlat?)(new CharacterModelFlat()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CharactersLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<PlayerProfileFlat> CreatePlayerProfileFlat(FlatBufferBuilder builder,
      int gold = 0,
      StringOffset itemsOffset = default(StringOffset),
      VectorOffset charactersOffset = default(VectorOffset)) {
    builder.StartObject(3);
    PlayerProfileFlat.AddCharacters(builder, charactersOffset);
    PlayerProfileFlat.AddItems(builder, itemsOffset);
    PlayerProfileFlat.AddGold(builder, gold);
    return PlayerProfileFlat.EndPlayerProfileFlat(builder);
  }

  public static void StartPlayerProfileFlat(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddGold(FlatBufferBuilder builder, int gold) { builder.AddInt(0, gold, 0); }
  public static void AddItems(FlatBufferBuilder builder, StringOffset itemsOffset) { builder.AddOffset(1, itemsOffset.Value, 0); }
  public static void AddCharacters(FlatBufferBuilder builder, VectorOffset charactersOffset) { builder.AddOffset(2, charactersOffset.Value, 0); }
  public static VectorOffset CreateCharactersVector(FlatBufferBuilder builder, Offset<CharacterModelFlat>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartCharactersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PlayerProfileFlat> EndPlayerProfileFlat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PlayerProfileFlat>(o);
  }
  public static void FinishPlayerProfileFlatBuffer(FlatBufferBuilder builder, Offset<PlayerProfileFlat> offset) { builder.Finish(offset.Value, "FPCS"); }
};

public struct MainCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MainCharacter GetRootAsMainCharacter(ByteBuffer _bb) { return GetRootAsMainCharacter(_bb, new MainCharacter()); }
  public static MainCharacter GetRootAsMainCharacter(ByteBuffer _bb, MainCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MainCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Fame { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Leadership { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<MainCharacter> CreateMainCharacter(FlatBufferBuilder builder,
      int fame = 0,
      int leadership = 0) {
    builder.StartObject(2);
    MainCharacter.AddLeadership(builder, leadership);
    MainCharacter.AddFame(builder, fame);
    return MainCharacter.EndMainCharacter(builder);
  }

  public static void StartMainCharacter(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddFame(FlatBufferBuilder builder, int fame) { builder.AddInt(0, fame, 0); }
  public static void AddLeadership(FlatBufferBuilder builder, int leadership) { builder.AddInt(1, leadership, 0); }
  public static Offset<MainCharacter> EndMainCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MainCharacter>(o);
  }
};

public struct Party : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Party GetRootAsParty(ByteBuffer _bb) { return GetRootAsParty(_bb, new Party()); }
  public static Party GetRootAsParty(ByteBuffer _bb, Party obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Party __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int One { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Two { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Three { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Party> CreateParty(FlatBufferBuilder builder,
      int one = 0,
      int two = 0,
      int three = 0) {
    builder.StartObject(3);
    Party.AddThree(builder, three);
    Party.AddTwo(builder, two);
    Party.AddOne(builder, one);
    return Party.EndParty(builder);
  }

  public static void StartParty(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddOne(FlatBufferBuilder builder, int one) { builder.AddInt(0, one, 0); }
  public static void AddTwo(FlatBufferBuilder builder, int two) { builder.AddInt(1, two, 0); }
  public static void AddThree(FlatBufferBuilder builder, int three) { builder.AddInt(2, three, 0); }
  public static Offset<Party> EndParty(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Party>(o);
  }
};

public struct CharacterModelFlat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CharacterModelFlat GetRootAsCharacterModelFlat(ByteBuffer _bb) { return GetRootAsCharacterModelFlat(_bb, new CharacterModelFlat()); }
  public static CharacterModelFlat GetRootAsCharacterModelFlat(ByteBuffer _bb, CharacterModelFlat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CharacterModelFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Exp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool LevelUp { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string LearnActive { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetLearnActiveBytes() { return __p.__vector_as_arraysegment(12); }
  public string Actives { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetActivesBytes() { return __p.__vector_as_arraysegment(14); }
  public string Traits { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetTraitsBytes() { return __p.__vector_as_arraysegment(16); }
  public AttributeFlat? Att { get { int o = __p.__offset(18); return o != 0 ? (AttributeFlat?)(new AttributeFlat()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CharacterModelFlat> CreateCharacterModelFlat(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int level = 0,
      int exp = 0,
      bool levelUp = false,
      StringOffset learnActiveOffset = default(StringOffset),
      StringOffset activesOffset = default(StringOffset),
      StringOffset traitsOffset = default(StringOffset),
      Offset<AttributeFlat> attOffset = default(Offset<AttributeFlat>)) {
    builder.StartObject(8);
    CharacterModelFlat.AddAtt(builder, attOffset);
    CharacterModelFlat.AddTraits(builder, traitsOffset);
    CharacterModelFlat.AddActives(builder, activesOffset);
    CharacterModelFlat.AddLearnActive(builder, learnActiveOffset);
    CharacterModelFlat.AddExp(builder, exp);
    CharacterModelFlat.AddLevel(builder, level);
    CharacterModelFlat.AddName(builder, nameOffset);
    CharacterModelFlat.AddLevelUp(builder, levelUp);
    return CharacterModelFlat.EndCharacterModelFlat(builder);
  }

  public static void StartCharacterModelFlat(FlatBufferBuilder builder) { builder.StartObject(8); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddExp(FlatBufferBuilder builder, int exp) { builder.AddInt(2, exp, 0); }
  public static void AddLevelUp(FlatBufferBuilder builder, bool levelUp) { builder.AddBool(3, levelUp, false); }
  public static void AddLearnActive(FlatBufferBuilder builder, StringOffset learnActiveOffset) { builder.AddOffset(4, learnActiveOffset.Value, 0); }
  public static void AddActives(FlatBufferBuilder builder, StringOffset activesOffset) { builder.AddOffset(5, activesOffset.Value, 0); }
  public static void AddTraits(FlatBufferBuilder builder, StringOffset traitsOffset) { builder.AddOffset(6, traitsOffset.Value, 0); }
  public static void AddAtt(FlatBufferBuilder builder, Offset<AttributeFlat> attOffset) { builder.AddOffset(7, attOffset.Value, 0); }
  public static Offset<CharacterModelFlat> EndCharacterModelFlat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterModelFlat>(o);
  }
};

public struct AttributeFlat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AttributeFlat GetRootAsAttributeFlat(ByteBuffer _bb) { return GetRootAsAttributeFlat(_bb, new AttributeFlat()); }
  public static AttributeFlat GetRootAsAttributeFlat(ByteBuffer _bb, AttributeFlat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AttributeFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Str { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Agi { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Intel { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int End { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Wisdom { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Cons { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Speed { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<AttributeFlat> CreateAttributeFlat(FlatBufferBuilder builder,
      int str = 0,
      int agi = 0,
      int intel = 0,
      int end = 0,
      int wisdom = 0,
      int cons = 0,
      int speed = 0) {
    builder.StartObject(7);
    AttributeFlat.AddSpeed(builder, speed);
    AttributeFlat.AddCons(builder, cons);
    AttributeFlat.AddWisdom(builder, wisdom);
    AttributeFlat.AddEnd(builder, end);
    AttributeFlat.AddIntel(builder, intel);
    AttributeFlat.AddAgi(builder, agi);
    AttributeFlat.AddStr(builder, str);
    return AttributeFlat.EndAttributeFlat(builder);
  }

  public static void StartAttributeFlat(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddStr(FlatBufferBuilder builder, int str) { builder.AddInt(0, str, 0); }
  public static void AddAgi(FlatBufferBuilder builder, int agi) { builder.AddInt(1, agi, 0); }
  public static void AddIntel(FlatBufferBuilder builder, int intel) { builder.AddInt(2, intel, 0); }
  public static void AddEnd(FlatBufferBuilder builder, int end) { builder.AddInt(3, end, 0); }
  public static void AddWisdom(FlatBufferBuilder builder, int wisdom) { builder.AddInt(4, wisdom, 0); }
  public static void AddCons(FlatBufferBuilder builder, int cons) { builder.AddInt(5, cons, 0); }
  public static void AddSpeed(FlatBufferBuilder builder, int speed) { builder.AddInt(6, speed, 0); }
  public static Offset<AttributeFlat> EndAttributeFlat(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AttributeFlat>(o);
  }
};

